name: 'Collect Testing Logs'
description: 'test-logs, coverage, pods'
runs:
  using: "composite"
  steps:
    - name: "Gather Logs"
      shell: bash
      run: |
        rsync \
          --prune-empty-dirs --archive --include='*/' \
          --include='*.xml' \
          --include='*.tap' \
          --include='*.log' \
          --include='Test*.webm' \
          --exclude='*' \
          . \
          /tmp/test-logs
        if test -d ~/.cache/telepresence/logs; then
          rsync \
            --archive \
            ~/.cache/telepresence/logs \
            /tmp/test-logs/telepresence-logs
        fi
        if test -e docker/kat-client.go.layer.tar && test -e docker/.tmp.kat-client.go.layer.tar.tmp; then
          cp docker/kat-client.go.layer.tar docker/.tmp.kat-client.go.layer.tar.tmp /tmp/test-logs
        fi
        if [ -f docker/container.txt ] && docker inspect $(cat docker/container.txt) >/dev/null; then
          docker exec $(cat docker/container.txt) /bin/bash -c 'mkdir -p /tmp/build-container-logs && (cp -r /tmp/*.txt /tmp/*.json /tmp/*.log /tmp/*.yaml /tmp/build-container-logs || true) && ((test -d ~/.cache/telepresence/logs && cp -r ~/.cache/telepresence/logs /tmp/build-container-logs/telepresence-logs) || true)'
          docker cp $(cat docker/container.txt):/tmp/build-container-logs /tmp/test-logs/build-container-logs || true
        fi
    - name: "Gather Coverage"
      shell: bash
      run: |
        if [ -f docker/container.txt ] && docker inspect $(cat docker/container.txt) >/dev/null; then
          docker cp $(cat docker/container.txt):/tmp/cov_html /tmp/cov_html || true
        fi
    - name: "Gather Pod Logs"
      shell: bash
      run: |
        if ! test -f ~/.kube/config; then
          exit 0
        fi

        make tools/bin/kubectl

        mkdir -p /tmp/pod-logs
        podsfile=/tmp/pod-logs/all-pods.txt
        (tools/bin/kubectl get pods --all-namespaces -ocustom-columns="name:.metadata.name,namespace:.metadata.namespace " --no-headers || true) > $podsfile
        (tools/bin/kubectl describe pods --all-namespaces || true) > /tmp/pod-logs/all-pods-described.txt

        cat $podsfile | while IFS= read -r line; do
          name=$(echo $line | awk '{print $1}')
          ns=$(echo $line | awk '{print $2}')
          nsdir=/tmp/pod-logs/${ns}/
          mkdir -p $nsdir
          outfile=${nsdir}/${name}-pod.log
          (tools/bin/kubectl logs -n $ns $name > $outfile || echo "FAILED, status $ret, continuing...") || true
        done
    # upload artifacts
    - name: "Upload Test Logs (test-logs)"
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PREFIX }}--test-logs
        path: /tmp/test-logs
        if-no-files-found: ignore
    - name: "Upload Cov Logs (cov_html)"
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PREFIX }}--cov_html
        path: /tmp/cov_html
        if-no-files-found: ignore
    - name: "Upload Pod Logs (pod-logs)"
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PREFIX }}--pod-logs
        path: /tmp/pod-logs
        if-no-files-found: ignore
    - name: "Upload XML Logs (xml)"
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PREFIX }}--xml
        path: /tmp/test-logs/xml/
        if-no-files-found: ignore
