apiVersion: v1
entries:
  ambassador:
  - apiVersion: v1
    appVersion: 1.13.10
    created: "2022-02-10T19:34:52.751885+09:00"
    description: A Helm chart for Datawire Ambassador
    digest: 726d25206ff52427f5aa53cb763e85063911f2bb8719dd9eafd2ffa7cfd9dde4
    home: https://www.getambassador.io/
    icon: https://www.getambassador.io/images/logo.png
    keywords:
    - api gateway
    - ambassador
    - datawire
    - envoy
    maintainers:
    - email: markus@maga.se
      name: flydiverny
    - email: flynn@datawire.io
      name: kflynn
    - email: nkrause@datawire.io
      name: nbkrause
    - email: lukeshu@datawire.io
      name: lukeshu
    name: ambassador
    sources:
    - https://github.com/datawire/ambassador
    - https://github.com/prometheus/statsd_exporter
    urls:
    - ambassador-6.7.13.tgz
    version: 6.7.13
generated: "2022-02-10T19:34:52.74516+09:00"
